import { PelangganIndustri, PemakaianAir, HasilLabHarian, InfoPelayanan, TiketLayanan } from '../types';

export const INITIAL_PELANGGAN: PelangganIndustri[] = [
  {
    id_pelanggan: 'AETRA-IND-001',
    nama_perusahaan: 'PT Indofood CBP Sukses Makmur Tbk',
    bidang_usaha: 'Industri Makanan & Minuman (Noodle & Snack Division)',
    alamat_kawasan: 'Kawasan Industri Cikupa Mas Blok A2 No. 8, Tangerang',
    zona_distribusi: 'Zona Cikupa - Balaraja (IPA Cikokol)',
    pic_nama: 'Ir. Budi Santoso',
    pic_telepon: '+62 812-8890-1122',
    email: 'utility.cikupa@indofood.co.id',
    no_meter: 'MTR-CKP-00918',
    password: 'indofood123',
    status_aktif: true,
    created_at: '2026-01-10T08:00:00Z'
  },
  {
    id_pelanggan: 'AETRA-IND-002',
    nama_perusahaan: 'PT Mayora Indah Tbk',
    bidang_usaha: 'Industri Biskuit & Kembang Gula',
    alamat_kawasan: 'Jl. Telesonic Ujung, Kawasan Industri Jatake, Tangerang',
    zona_distribusi: 'Zona Jatake - Pasar Kemis (IPA Sepatan)',
    pic_nama: 'Hendro Prasetyo, S.T.',
    pic_telepon: '+62 813-7744-9988',
    email: 'eng.jatake@mayora.co.id',
    no_meter: 'MTR-JTK-04821',
    password: 'mayora123',
    status_aktif: true,
    created_at: '2026-01-12T09:00:00Z'
  },
  {
    id_pelanggan: 'AETRA-IND-003',
    nama_perusahaan: 'PT Torabika Eka Semesta',
    bidang_usaha: 'Industri Pengolahan Kopi & Minuman Serbuk',
    alamat_kawasan: 'Kawasan Industri Manis, Jl. Manis V No. 18, Tangerang',
    zona_distribusi: 'Zona Manis - Jatake',
    pic_nama: 'Siti Rahmawati',
    pic_telepon: '+62 811-9922-3344',
    email: 'facility.manis@torabika.com',
    no_meter: 'MTR-MNS-01290',
    password: 'torabika123',
    status_aktif: true,
    created_at: '2026-01-15T10:00:00Z'
  },
  {
    id_pelanggan: 'AETRA-IND-004',
    nama_perusahaan: 'PT Gajah Tunggal Tbk',
    bidang_usaha: 'Industri Otomotif, Ban & Karet Sintetis',
    alamat_kawasan: 'Kawasan Industri Gajah Tunggal, Jatiuwung, Tangerang',
    zona_distribusi: 'Zona Jatiuwung Barat (Booster Station)',
    pic_nama: 'Bambang Kusumo',
    pic_telepon: '+62 815-6677-8899',
    email: 'tech.plant@gt-tires.com',
    no_meter: 'MTR-JTW-08172',
    password: 'gajah123',
    status_aktif: true,
    created_at: '2026-01-05T07:30:00Z'
  },
  {
    id_pelanggan: 'AETRA-IND-005',
    nama_perusahaan: 'PT Unilever Oleochemical',
    bidang_usaha: 'Industri Oleokimia & Bahan Baku Sabun',
    alamat_kawasan: 'Balaraja Industrial Estate Kav. 12, Tangerang',
    zona_distribusi: 'Zona Balaraja Barat',
    pic_nama: 'Dewi Lestari',
    pic_telepon: '+62 812-3355-7799',
    email: 'hse.balaraja@unilever.com',
    no_meter: 'MTR-BLR-03120',
    password: 'unilever123',
    status_aktif: true,
    created_at: '2026-01-18T11:00:00Z'
  }
];

export const INITIAL_PEMAKAIAN: PemakaianAir[] = [
  // AETRA-IND-001 (Indofood) - Tahap: Terverifikasi
  {
    id: 'pmk-001',
    id_pelanggan: 'AETRA-IND-001',
    periode_bulan: 'September',
    periode_tahun: 2026,
    tanggal_baca: '2026-09-20',
    meter_awal: 184520,
    meter_akhir: 198340,
    total_m3: 13820,
    status_progress: 'Terverifikasi',
    no_bpm: 'BPM/2026/09/CKP-001',
    tanggal_bpm: '2026-09-18',
    tanggal_verifikasi: '2026-09-21',
    catatan_petugas: 'Pembacaan meter berjalan lancar. Segel meter utuh dan akurat.',
    nama_staf_pencatat: 'Reza Fauzan (Key Account Field Tech)',
    created_at: '2026-09-20T14:30:00Z'
  },
  {
    id: 'pmk-002',
    id_pelanggan: 'AETRA-IND-001',
    periode_bulan: 'Agustus',
    periode_tahun: 2026,
    tanggal_baca: '2026-08-20',
    meter_awal: 170400,
    meter_akhir: 184520,
    total_m3: 14120,
    status_progress: 'Terverifikasi',
    no_bpm: 'BPM/2026/08/CKP-001',
    tanggal_bpm: '2026-08-18',
    tanggal_verifikasi: '2026-08-21',
    catatan_petugas: 'Kondisi flow meter normal, tidak ada deviasi tekanan.',
    nama_staf_pencatat: 'Reza Fauzan (Key Account Field Tech)',
    created_at: '2026-08-20T11:15:00Z'
  },
  {
    id: 'pmk-003',
    id_pelanggan: 'AETRA-IND-001',
    periode_bulan: 'Juli',
    periode_tahun: 2026,
    tanggal_baca: '2026-07-21',
    meter_awal: 156900,
    meter_akhir: 170400,
    total_m3: 13500,
    status_progress: 'Terverifikasi',
    no_bpm: 'BPM/2026/07/CKP-001',
    tanggal_bpm: '2026-07-19',
    tanggal_verifikasi: '2026-07-22',
    catatan_petugas: 'Sesuai jadwal rutin.',
    nama_staf_pencatat: 'Reza Fauzan (Key Account Field Tech)',
    created_at: '2026-07-21T09:00:00Z'
  },

  // AETRA-IND-002 (Mayora) - Tahap: Pembacaan Meter (Sedang proses verifikasi)
  {
    id: 'pmk-004',
    id_pelanggan: 'AETRA-IND-002',
    periode_bulan: 'September',
    periode_tahun: 2026,
    tanggal_baca: '2026-09-22',
    meter_awal: 92140,
    meter_akhir: 99880,
    total_m3: 7740,
    status_progress: 'Pembacaan Meter',
    no_bpm: 'BPM/2026/09/JTK-002',
    tanggal_bpm: '2026-09-20',
    catatan_petugas: 'Stand meter selesai dicatat di lokasi pabrik Jatake. Menunggu verifikasi supervisor.',
    nama_staf_pencatat: 'Dian Permana (Staf Key Account)',
    created_at: '2026-09-22T13:40:00Z'
  },
  {
    id: 'pmk-005',
    id_pelanggan: 'AETRA-IND-002',
    periode_bulan: 'Agustus',
    periode_tahun: 2026,
    tanggal_baca: '2026-08-21',
    meter_awal: 84300,
    meter_akhir: 92140,
    total_m3: 7840,
    status_progress: 'Terverifikasi',
    no_bpm: 'BPM/2026/08/JTK-002',
    tanggal_bpm: '2026-08-19',
    tanggal_verifikasi: '2026-08-22',
    catatan_petugas: 'Normal.',
    nama_staf_pencatat: 'Dian Permana (Staf Key Account)',
    created_at: '2026-08-21T14:10:00Z'
  },

  // AETRA-IND-003 (Torabika) - Tahap: Penerbitan BPM (Surat perintah baca meter terbit, teknisi akan menuju lokasi)
  {
    id: 'pmk-006',
    id_pelanggan: 'AETRA-IND-003',
    periode_bulan: 'September',
    periode_tahun: 2026,
    tanggal_baca: '2026-09-24',
    meter_awal: 54100,
    meter_akhir: 54100,
    total_m3: 0,
    status_progress: 'Penerbitan BPM',
    no_bpm: 'BPM/2026/09/MNS-003',
    tanggal_bpm: '2026-09-23',
    catatan_petugas: 'Surat Bukti Pembacaan Meter (BPM) telah diterbitkan kantor Aetra. Jadwal pencatatan hari ini.',
    nama_staf_pencatat: 'Budi Santoso, S.T. (Key Account Executive)',
    created_at: '2026-09-23T07:30:00Z'
  },
  {
    id: 'pmk-007',
    id_pelanggan: 'AETRA-IND-003',
    periode_bulan: 'Agustus',
    periode_tahun: 2026,
    tanggal_baca: '2026-08-22',
    meter_awal: 47580,
    meter_akhir: 54100,
    total_m3: 6520,
    status_progress: 'Terverifikasi',
    no_bpm: 'BPM/2026/08/MNS-003',
    tanggal_bpm: '2026-08-20',
    tanggal_verifikasi: '2026-08-23',
    catatan_petugas: 'Display meter digital terbaca jelas.',
    nama_staf_pencatat: 'Dian Permana (Staf Key Account)',
    created_at: '2026-08-22T10:20:00Z'
  },

  // AETRA-IND-004 (Gajah Tunggal) - Tahap: Terverifikasi
  {
    id: 'pmk-008',
    id_pelanggan: 'AETRA-IND-004',
    periode_bulan: 'September',
    periode_tahun: 2026,
    tanggal_baca: '2026-09-19',
    meter_awal: 412500,
    meter_akhir: 434900,
    total_m3: 22400,
    status_progress: 'Terverifikasi',
    no_bpm: 'BPM/2026/09/JTW-004',
    tanggal_bpm: '2026-09-17',
    tanggal_verifikasi: '2026-09-20',
    catatan_petugas: 'Pabrik ban beroperasi 3 shift, debit stabil di 3.8 bar.',
    nama_staf_pencatat: 'Ahmad Fauzi (Senior Key Account)',
    created_at: '2026-09-19T16:00:00Z'
  }
];

export const INITIAL_LAB_RESULTS: HasilLabHarian[] = [
  // 1. Kategori 1: Hasil Uji Lab Reservoar IPA (Sepatan)
  {
    id: 'lab-001',
    judul_dokumen: 'Hasil Uji Mutu Air Reservoar Distribusi Utama IPA Sepatan',
    kategori_lab: 'Reservoar IPA',
    tanggal_uji: '2026-09-27',
    waktu_sampling: '07:30 WIB',
    lokasi_sampling: 'Bak Penampungan & Reservoar Utama IPA Sepatan Tangerang',
    nama_analis_lab: 'Nurul Hidayati, S.Si (Analis Pengendalian Mutu)',
    no_sertifikat_lab: 'COA-IPA/AETRA/2026/09-0112',
    pdf_filename: 'Laporan_Uji_Lab_Reservoar_IPA_Sepatan_Sep2026.pdf',
    pdf_size: '1.8 MB',
    status_kelayakan: 'MEMENUHI SYARAT (Permenkes No. 2/2023)',
    catatan: 'Seluruh parameter mikrobiologi, kimia, dan fisika pada air olahan reservoar dinyatakan steril dan layak minum.',
    ph: 7.35,
    kekeruhan_ntu: 0.32,
    sisa_khlor_mg_l: 0.38,
    tds_mg_l: 138,
    suhu_celsius: 27.2,
    e_coli_cfu: 0,
    rasa_bau: 'Tidak Berbau & Normal',
    created_at: '2026-09-27T08:15:00Z'
  },
  {
    id: 'lab-002',
    judul_dokumen: 'Hasil Uji Mutu Air Reservoar IPA Sepatan Tangerang',
    kategori_lab: 'Reservoar IPA',
    tanggal_uji: '2026-09-25',
    waktu_sampling: '08:00 WIB',
    lokasi_sampling: 'Reservoar Distribusi Utara IPA Sepatan',
    nama_analis_lab: 'Nurul Hidayati, S.Si (Analis Pengendalian Mutu)',
    no_sertifikat_lab: 'COA-IPA/AETRA/2026/09-0110',
    pdf_filename: 'Laporan_Uji_Lab_Reservoar_IPA_Sepatan_Sep2026.pdf',
    pdf_size: '1.6 MB',
    status_kelayakan: 'MEMENUHI SYARAT (Permenkes No. 2/2023)',
    catatan: 'Kualitas air jernih stabil dengan desinfeksi optimal.',
    ph: 7.28,
    kekeruhan_ntu: 0.39,
    sisa_khlor_mg_l: 0.35,
    tds_mg_l: 145,
    suhu_celsius: 27.5,
    e_coli_cfu: 0,
    rasa_bau: 'Tidak Berbau & Normal',
    created_at: '2026-09-25T08:45:00Z'
  },

  // 2. Kategori 2: Hasil Uji Lab Reservoar Booster
  {
    id: 'lab-003',
    judul_dokumen: 'Hasil Uji Mutu Air Stasiun Pompa Reservoar Booster Jatiuwung',
    kategori_lab: 'Reservoar Booster',
    tanggal_uji: '2026-09-26',
    waktu_sampling: '09:15 WIB',
    lokasi_sampling: 'Outlet Discharge Booster Pump Station Jatiuwung & Pasir Jaya',
    nama_analis_lab: 'Dian Permana (Laboratorium Lapangan)',
    no_sertifikat_lab: 'COA-BST/AETRA/2026/09-0205',
    pdf_filename: 'Laporan_Uji_Lab_Reservoar_Booster_Jatiuwung_Sep2026.pdf',
    pdf_size: '1.5 MB',
    status_kelayakan: 'MEMENUHI SYARAT (Permenkes No. 2/2023)',
    catatan: 'Klor sisa terjaga baik di jaringan pompa dorong, aman untuk transmisi bertekanan tinggi.',
    ph: 7.30,
    kekeruhan_ntu: 0.41,
    sisa_khlor_mg_l: 0.36,
    tds_mg_l: 140,
    suhu_celsius: 27.4,
    e_coli_cfu: 0,
    rasa_bau: 'Tidak Berbau & Normal',
    created_at: '2026-09-26T10:00:00Z'
  },
  {
    id: 'lab-004',
    judul_dokumen: 'Hasil Uji Mutu Air Stasiun Pompa Reservoar Booster Cikupa Mas',
    kategori_lab: 'Reservoar Booster',
    tanggal_uji: '2026-09-24',
    waktu_sampling: '08:45 WIB',
    lokasi_sampling: 'Booster Pump Station Cikupa Mas Blok Central',
    nama_analis_lab: 'Dian Permana (Laboratorium Lapangan)',
    no_sertifikat_lab: 'COA-BST/AETRA/2026/09-0201',
    pdf_filename: 'Laporan_Uji_Lab_Reservoar_Booster_Cikupa_Sep2026.pdf',
    pdf_size: '1.4 MB',
    status_kelayakan: 'MEMENUHI SYARAT (Permenkes No. 2/2023)',
    catatan: 'Tekanan dorong 3.6 bar dengan mutu air memenuhi standar industri pangan.',
    ph: 7.38,
    kekeruhan_ntu: 0.36,
    sisa_khlor_mg_l: 0.34,
    tds_mg_l: 144,
    suhu_celsius: 27.1,
    e_coli_cfu: 0,
    rasa_bau: 'Tidak Berbau & Normal',
    created_at: '2026-09-24T09:30:00Z'
  },

  // 3. Kategori 3: Hasil Uji Lab Industri (Personalized)
  {
    id: 'lab-005',
    judul_dokumen: 'Hasil Uji Mutu Air Industri - PT Indofood CBP Sukses Makmur Tbk',
    kategori_lab: 'Industri',
    id_pelanggan_khusus: 'AETRA-IND-001',
    nama_perusahaan_khusus: 'PT Indofood CBP Sukses Makmur Tbk',
    tanggal_uji: '2026-09-26',
    waktu_sampling: '10:30 WIB',
    lokasi_sampling: 'Inlet Header Tangki Utama Pabrik F&B PT Indofood CBP, Cikupa',
    nama_analis_lab: 'Nurul Hidayati, S.Si (Spesialis Mutu Industri)',
    no_sertifikat_lab: 'COA-IND/AETRA/IND-001/2026-09',
    pdf_filename: 'Laporan_Uji_Lab_Industri_PT_Indofood_CBP_Sep2026.pdf',
    pdf_size: '2.1 MB',
    status_kelayakan: 'MEMENUHI SYARAT (Permenkes No. 2/2023 - Grade Pangan)',
    catatan: 'Sampling resmi in-plant bersama perwakilan QA/QC PT Indofood. Seluruh parameter fisika kimia dan biologis lolos kriteria food-grade utility.',
    ph: 7.32,
    kekeruhan_ntu: 0.28,
    sisa_khlor_mg_l: 0.32,
    tds_mg_l: 135,
    suhu_celsius: 26.9,
    e_coli_cfu: 0,
    rasa_bau: 'Sangat Bersih, Normal & Tidak Berbau',
    created_at: '2026-09-26T11:45:00Z'
  },
  {
    id: 'lab-006',
    judul_dokumen: 'Hasil Uji Mutu Air Industri - PT Mayora Indah Tbk',
    kategori_lab: 'Industri',
    id_pelanggan_khusus: 'AETRA-IND-002',
    nama_perusahaan_khusus: 'PT Mayora Indah Tbk',
    tanggal_uji: '2026-09-25',
    waktu_sampling: '11:00 WIB',
    lokasi_sampling: 'Titik Sambungan Meter Induk & Tandon PT Mayora Indah, Jatake',
    nama_analis_lab: 'Nurul Hidayati, S.Si (Spesialis Mutu Industri)',
    no_sertifikat_lab: 'COA-IND/AETRA/IND-002/2026-09',
    pdf_filename: 'Laporan_Uji_Lab_Industri_PT_Mayora_Indah_Sep2026.pdf',
    pdf_size: '1.9 MB',
    status_kelayakan: 'MEMENUHI SYARAT (Permenkes No. 2/2023)',
    catatan: 'Pengujian on-site berkala atas permohonan tim engineering PT Mayora Indah Tbk.',
    ph: 7.34,
    kekeruhan_ntu: 0.30,
    sisa_khlor_mg_l: 0.33,
    tds_mg_l: 139,
    suhu_celsius: 27.0,
    e_coli_cfu: 0,
    rasa_bau: 'Normal & Tidak Berbau',
    created_at: '2026-09-25T13:00:00Z'
  }
];

export const INITIAL_INFO_PELAYANAN: InfoPelayanan[] = [
  {
    id: 'info-001',
    judul: 'Pemeliharaan Pipa Transmisi Induk & Penyesuaian Tekanan Zona Industri Cikupa - Jatake',
    tipe: 'Pemeliharaan Jaringan',
    tingkat_urgensi: 'Penting',
    tanggal_mulai: '2026-09-28 22:00',
    tanggal_selesai: '2026-09-29 04:30',
    wilayah_terdampak: 'Kawasan Industri Jatake, Kawasan Industri Manis, dan Cikupa Mas',
    deskripsi: 'Pekerjaan preventif maintenance koneksi valve transmisi primer dan pembersihan filter inlet booster. Dilakukan pada jam operasional minim untuk menekan dampak pada utilitas industri.',
    status_aliran: 'Penurunan Tekanan Sementara',
    solusi_mitigasi: 'Pelanggan industri dihimbau mengoptimalkan penampungan ground water tank sebelum pukul 21:00 WIB. Tim teknis dan armada truk tangki siaga 24 jam.',
    pic_nama: 'Ahmad Fauzi (Supervisor Key Account)',
    pic_kontak: '+62 811-9988-7711 (WhatsApp / Telp)',
    status_publikasi: true,
    tampilkan_banner: true,
    created_at: '2026-09-27T10:00:00Z'
  },
  {
    id: 'info-002',
    judul: 'Pemberitahuan Perbaikan Pipa Distribusi Darurat Sekitar Jalur Boulevard Manis',
    tipe: 'Perbaikan Pipa Darurat',
    tingkat_urgensi: 'Darurat',
    tanggal_mulai: '2026-09-28 08:00',
    tanggal_selesai: '2026-09-28 14:00',
    wilayah_terdampak: 'Kawasan Industri Manis Blok F dan sebagian Pasir Jaya',
    deskripsi: 'Penanganan darurat kebocoran sambungan pipa pipa baja DN 300 akibat pergeseran tanah. Aliran dialihkan bertahap melalui bypass sekunder.',
    status_aliran: 'Pemadaman Sementara Terjadwal',
    solusi_mitigasi: 'Bantuan armada air bersih darurat Aetra disiapkan gratis untuk industri terdampak via call center 0811-1900-223.',
    pic_nama: 'Reza Fauzan (Koordinator Lapangan)',
    pic_kontak: '+62 812-8877-6655',
    status_publikasi: true,
    tampilkan_banner: true,
    created_at: '2026-09-28T07:30:00Z'
  },
  {
    id: 'info-003',
    judul: 'Flushing Rutin Berkala Pipa Distribusi Utama Sepatan - Balaraja',
    tipe: 'Flushing Pipa',
    tingkat_urgensi: 'Normal',
    tanggal_mulai: '2026-10-02 01:00',
    tanggal_selesai: '2026-10-02 04:00',
    wilayah_terdampak: 'Kawasan Industri Balaraja Barat & Jalur Serang KM 28',
    deskripsi: 'Pembersihan endapan mineral pipa secara berkala demi menjamin kejernihan air minum sesuai standar Permenkes No. 2/2023.',
    status_aliran: 'Terganggu Terjadwal',
    solusi_mitigasi: 'Operasional boiler dan sistem RO dapat berjalan normal menggunakan cadangan tangki internal.',
    pic_nama: 'Dian Permana (Teknisi Jaringan)',
    pic_kontak: '+62 813-1122-3344',
    status_publikasi: true,
    tampilkan_banner: false,
    created_at: '2026-09-26T15:00:00Z'
  }
];

export const INITIAL_TIKET: TiketLayanan[] = [
  {
    id: 'tkt-001',
    id_pelanggan: 'AETRA-IND-002',
    perihal: 'Rembesan air bertekanan tinggi pada sambungan pipa dinas inlet',
    kategori: 'Laporan bocor sebelum meter/pipa dinas',
    pesan: 'Ditemukan kebocoran bertekanan pada pipa dinas sebelum flow meter induk pabrik Mayora Manis. Mohon penanganan darurat dari tim perbaikan pipa Aetra sebelum menggenangi area loading dock.',
    status: 'Terkirim',
    status_tindak_lanjut: 'Belum Ditindaklanjuti',
    urgensi: 'Darurat',
    created_at: '2026-09-28T09:15:00Z'
  },
  {
    id: 'tkt-002',
    id_pelanggan: 'AETRA-IND-003',
    perihal: 'Tekanan suplai air drop di bawah 1.5 bar sejak pagi',
    kategori: 'Laporan air kecil/tidak mengalir',
    pesan: 'Tekanan air inlet instalasi saniter pabrik menurun drastis di bawah standar kontinuitas industri (biasanya 3.5 bar). Mohon pengecekan jaringan booster pengumpan wilayah Cikupa Mas.',
    status: 'Diteruskan ke CC',
    status_tindak_lanjut: 'Diteruskan ke CC',
    urgensi: 'Tinggi',
    no_tiket_cc: 'CC-AETRA-2026-0814',
    divisi_tujuan: 'Divisi Pemeliharaan Jaringan & Distribusi',
    catatan_internal_cc: 'Prioritas tinggi. Dispatch tim teknisi flushing dan cek valve pembagi sekunder Balaraja/Cikupa. Pelanggan butuh kontinuitas untuk boiler.',
    respon_petugas: 'Laporan telah kami terima dan dieskalasikan ke Divisi Distribusi & Contact Center 24 Jam dengan No. Tiket CC-AETRA-2026-0814. Tim operasional jaringan sedang melakukan penyesuaian valve booster.',
    tanggal_tindak_lanjut: '2026-09-28T10:00:00Z',
    nama_petugas_tindak_lanjut: 'Hendra Wijaya, M.T. (Admin Key Account)',
    openbravo_case_created: true,
    no_case_openbravo: 'OB-CASE-2026-0814',
    tanggal_case_openbravo: '2026-09-28T10:15:00Z',
    petugas_case_openbravo: 'Siti Rahmawati, S.I.Kom. (Customer Care)',
    catatan_openbravo: 'Case dibuat di OpenBravo Modul Distribusi & Teknis. SPK pengecekan valve booster diterbitkan.',
    status_penanganan_cc: 'Dalam Proses CC',
    created_at: '2026-09-28T08:30:00Z'
  },
  {
    id: 'tkt-005',
    id_pelanggan: 'AETRA-IND-002',
    perihal: 'Fluktuasi debit air mendadak pada jalur pipa primer Cikupa',
    kategori: 'Laporan fluktuasi debit/tekanan',
    pesan: 'Mohon bantuan tim teknis Aetra untuk pengecekan inlet valve sekunder karena debit turun hingga 30% dari kapasitas normal jam produksi.',
    status: 'Diteruskan ke CC',
    status_tindak_lanjut: 'Diteruskan ke CC',
    urgensi: 'Tinggi',
    no_tiket_cc: 'CC-AETRA-2026-0932',
    divisi_tujuan: 'Divisi Contact Center (CC)',
    catatan_internal_cc: 'Mohon segera dibuatkan Case di OpenBravo dan koordinasikan dispatch tim mekanik jaringan pipa primer.',
    respon_petugas: 'Laporan Anda telah diverifikasi oleh Key Account dan diteruskan ke Contact Center (CC) dengan No. Tiket: CC-AETRA-2026-0932.',
    tanggal_tindak_lanjut: '2026-09-29T11:20:00Z',
    nama_petugas_tindak_lanjut: 'Hendra Wijaya, M.T. (Admin Key Account)',
    openbravo_case_created: false,
    status_penanganan_cc: 'Menunggu Input OB',
    created_at: '2026-09-29T10:45:00Z'
  },
  {
    id: 'tkt-003',
    id_pelanggan: 'AETRA-IND-001',
    perihal: 'Permohonan Tera Ulang Kalibrasi Flow Meter Utama Pabrik',
    kategori: 'Request Tera meter',
    pesan: 'Mohon dijadwalkan verifikasi dan kalibrasi bersama flow meter elektromagentik 6 inch menjelang audit tahunan ISO 14001 pada awal Oktober 2026.',
    status: 'Diproses',
    status_tindak_lanjut: 'Respon Langsung',
    urgensi: 'Sedang',
    divisi_tujuan: 'Divisi Meter & Instrumentasi Industri',
    respon_petugas: 'Petugas kalibrasi instrumentasi Aetra dijadwalkan hadir bersama tim teknik pabrik pada tanggal 2 Oktober 2026 pukul 09:30 WIB.',
    tanggal_tindak_lanjut: '2026-09-22T08:45:00Z',
    nama_petugas_tindak_lanjut: 'Budi Santoso, S.T. (Key Account Executive)',
    created_at: '2026-09-21T11:20:00Z'
  },
  {
    id: 'tkt-004',
    id_pelanggan: 'AETRA-IND-004',
    perihal: 'Permintaan Surat Konfirmasi Baku Mutu Air untuk Audit Green Building',
    kategori: 'Informasi pelanggan',
    pesan: 'Mohon dikirimkan salinan CoA (Certificate of Analysis) parameter mikrobiologi terbaru untuk lampiran audit sertifikasi gedung hijau.',
    status: 'Selesai',
    status_tindak_lanjut: 'Selesai',
    urgensi: 'Normal',
    respon_petugas: 'Dokumen sertifikat mutu air periode September 2026 telah diverifikasi tim lab dan telah kami unggah pada menu Hasil Uji Laboratorium portal perusahaan Anda.',
    tanggal_tindak_lanjut: '2026-09-20T14:10:00Z',
    nama_petugas_tindak_lanjut: 'Dian Permana (Staf Key Account)',
    created_at: '2026-09-19T13:00:00Z'
  }
];
